services:
  vote:
    build: ./vote 
    depends_on:
      - redis
    ports:
      - "5000:80"

  result:
    build: ./result
    depends_on:
      -  db
    ports:
      - "5001:80"

  worker:
    build: ./worker
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  # this service runs once to seed the database with votes
  # it won't run unless you specify the "seed" profile
  seed:
    build: ./seed-data
    profiles: ["seed"]
    depends_on:
      - vote
